
FROM mysql:8.0

RUN curl -o /docker-entrypoint-initdb.d/contacts.sql https://raw.githubusercontent.com/michelnyobe/frontend_debops/master/contacts.sql

ENV MYSQL_ROOT_PASSWORD=root_password
ENV MYSQL_DATABASE=contacts

EXPOSE 3306
